### ISSUE TITLE
Authors first and last names are sorted differently when added manually or via DOI

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#334]

**Comment by NRayya** [comment]
<img width="1453" alt="image" src="https://user-images.githubusercontent.com/82588017/185100844-19ab0113-e8ba-4888-84b1-6018c4b9cef7.png">

The problem is still there in the public view of the project

**Comment by NishaSharma14** [comment]
Should be fixed now.

**Comment by NRayya** [comment]
I am facing the same issue now

**Comment by NishaSharma14** [comment]
are you facing this in both dev and prod?

**Comment by NRayya** [comment]
We still have a minor enhancement issue. The imported name from ORCID is still reversed in this view but this doesn't affect the tables or the project  dashboard view or the public one
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/82588017/224695255-e77f0216-53b8-4f89-a474-301d007cdc33.png">

**Comment by NRayya** [comment]
We need to re-check the new added projects
